### PR TITLE
Fix lists

### PR DESCRIPTION
**Pull request by davidfarmer**
The test which was  a "p" wrapping an "em" at the start of an li,
is now a title.

Not sure all cases were caught.

### CODE REVIEW

**Comment by rbeezer** [comment]
Faulty memory, there are **nested** `<em>` it seems.  Which appear to have done fine as source.  We'll see how they render, but at least they are preserved.

Partly so it can be re-created:

```bash
git diff master | grep '^+' | less -R | grep "<em"
```
```xml
<li><title><em>When you arrive at college,</em> build relationships with faculty</title>
<li><title><em>When you start thinking about applications,</em> identify which professor(s) you'd most like to write you a letter</title>
<li><title><em> When there there are 3<ndash/>5 days left before the application is due,</em> remind your professor that their letter is due soon</title>
<li><title><em>When you submit your application,</em> say thank you!</title>
<li><title>Keep your technology updated, and <em>back up your files.</em></title>
<li><title>Keep track of potential <em>career information.</em></title>
<li><title>Keep track of <em>medical and financial information.</em></title>
<li><title>Keep track of <em>miscellaneous activities</em> you've participated in</title>
```

**Comment by rbeezer** [comment]
Yep, I see those trapped periods.

**Comment by rbeezer** [comment]
All merged in, website is being updated right now.  Looks much, much better.  Thanks for the regex magic!  Bethany thanks you for saving her hours of drudgery during an upcoming glorious PNW summer day.

Extra periods trapped inside `em` cleaned up at c19701d4de6e669afe562391f05ba9b340f3e82c

Interior `li/title/em`  are not rendering (or can't be discerned) in LaTeX nor in HTML.  Not critical right now.

First non-UPS, post-open-license, contributor!

**Comment by davidfarmer** [comment]
It took more time for me to fork, clone, and do other overhead items
then it did to actually write the regular expressions and verify that
those worked.

In case it will help someone else in the future, this is all the code I   
wrote: 
```
    thetext = re.sub(r"<li>\s*<p>\s*<em>(.*?)</em>\s*</p>",
                     r"<li><title>\1</title>", thetext)

    thetext = re.sub(r"\.</title>", "</title>", thetext)
```

**Pull request merged**
